spring:
  datasource:
    url: jdbc:mysql://192.168.0.15:3306/jdbcrew_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: jdbcrew
    password: simon
    driver-class-name: com.mysql.cj.jdbc.Driver
